### Obtener todas las tareas
GET http://localhost:1234/tasks

### Obtener Tareas Completadas
GET http://localhost:1234/tasks?completed=true

###Obtener Tareas Incompletas
GET http://localhost:1234/tasks?completed=false

### Obtener Tareas de Prioridad Alta
GET http://localhost:1234/tasks?priority=high

### Obtener Tareas de Alta Prioridad Incompletas
GET http://localhost:1234/tasks?priority=high&completed=false

### Obtener Tarea por Id Valido
GET http://localhost:1234/tasks/1

### Obtener Tarea por Id Invalido
GET http://localhost:1234/tasks/9999

### Crear Tarea Valida
POST http://localhost:1234/tasks
Content-Type: application/json

{
    "title": "Nueva Tarea",
    "description": "Probar POST",
    "completed": true,
    "priority": "high"
}

### Crear Tarea sin todos los campos obligatorios
POST http://localhost:1234/tasks
Content-Type: application/json

{
    "title": "Nueva Tarea",
    "description": "Probar POST",
    "completed": true
}

### Actualizar Tarea
PUT http://localhost:1234/tasks/1
Content-Type: application/json

{
    "title": "Tarea Actualizada",
    "description": "Probar PUT",
    "completed": true,
    "priority": "high"
}

### Eliminar Tarea por id
DELETE http://localhost:1234/tasks/2

### En Vercel, el filesystem de las Serverless Functions no es persistente.
### tasks.json puede leerse, pero sus cambios con writeFile() no se garantizan
### entre ejecuciones. Para persistencia real se necesita una base de datos.

### en produccion solo funcionan los GET, me sirve para entender como funciona y este tipo de problemas que existen al hacer deploy
POST https://mini-api-tareas.vercel.app/tasks
Content-Type: application/json

{
    "title": "Nueva Tarea",
    "description": "Probar POST",
    "completed": true,
    "priority": "high"
}
### 
GET https://mini-api-tareas.vercel.app/tasks/99